"""Map old So codes (first 2 digits of SBD) -> new 34-province codes. Source: CV 1239/BGDĐT + QĐ19/TTg."""
PROVINCE_MAP = {
    '01': ('01', 'Hà Nội', 'Hà Nội'),
    '02': ('79', 'TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'),
    '03': ('31', 'Hải Phòng', 'Hải Phòng'),
    '04': ('48', 'Đà Nẵng', 'Đà Nẵng'),
    '05': ('08', 'Hà Giang', 'Tuyên Quang'),
    '06': ('04', 'Cao Bằng', 'Cao Bằng'),
    '07': ('12', 'Lai Châu', 'Lai Châu'),
    '08': ('15', 'Lào Cai', 'Lào Cai'),
    '09': ('08', 'Tuyên Quang', 'Tuyên Quang'),
    '10': ('20', 'Lạng Sơn', 'Lạng Sơn'),
    '11': ('19', 'Bắc Kạn', 'Thái Nguyên'),
    '12': ('19', 'Thái Nguyên', 'Thái Nguyên'),
    '13': ('15', 'Yên Bái', 'Lào Cai'),
    '14': ('14', 'Sơn La', 'Sơn La'),
    '15': ('25', 'Phú Thọ', 'Phú Thọ'),
    '16': ('25', 'Vĩnh Phúc', 'Phú Thọ'),
    '17': ('22', 'Quảng Ninh', 'Quảng Ninh'),
    '18': ('24', 'Bắc Giang', 'Bắc Ninh'),
    '19': ('24', 'Bắc Ninh', 'Bắc Ninh'),
    '21': ('31', 'Hải Dương', 'Hải Phòng'),
    '22': ('33', 'Hưng Yên', 'Hưng Yên'),
    '23': ('25', 'Hòa Bình', 'Phú Thọ'),
    '24': ('37', 'Hà Nam', 'Ninh Bình'),
    '25': ('37', 'Nam Định', 'Ninh Bình'),
    '26': ('33', 'Thái Bình', 'Hưng Yên'),
    '27': ('37', 'Ninh Bình', 'Ninh Bình'),
    '28': ('38', 'Thanh Hóa', 'Thanh Hóa'),
    '29': ('40', 'Nghệ An', 'Nghệ An'),
    '30': ('42', 'Hà Tĩnh', 'Hà Tĩnh'),
    '31': ('44', 'Quảng Bình', 'Quảng Trị'),
    '32': ('44', 'Quảng Trị', 'Quảng Trị'),
    '33': ('46', 'Thừa Thiên - Huế', 'Huế'),
    '34': ('48', 'Quảng Nam', 'Đà Nẵng'),
    '35': ('51', 'Quảng Ngãi', 'Quảng Ngãi'),
    '36': ('51', 'Kon Tum', 'Quảng Ngãi'),
    '37': ('52', 'Bình Định', 'Gia Lai'),
    '38': ('52', 'Gia Lai', 'Gia Lai'),
    '39': ('66', 'Phú Yên', 'Đắk Lắk'),
    '40': ('66', 'Đắk Lắk', 'Đắk Lắk'),
    '41': ('56', 'Khánh Hòa', 'Khánh Hòa'),
    '42': ('68', 'Lâm Đồng', 'Lâm Đồng'),
    '43': ('75', 'Bình Phước', 'Đồng Nai'),
    '44': ('79', 'Bình Dương', 'TP. Hồ Chí Minh'),
    '45': ('56', 'Ninh Thuận', 'Khánh Hòa'),
    '46': ('80', 'Tây Ninh', 'Tây Ninh'),
    '47': ('68', 'Bình Thuận', 'Lâm Đồng'),
    '48': ('75', 'Đồng Nai', 'Đồng Nai'),
    '49': ('80', 'Long An', 'Tây Ninh'),
    '50': ('82', 'Đồng Tháp', 'Đồng Tháp'),
    '51': ('91', 'An Giang', 'An Giang'),
    '52': ('79', 'Bà Rịa - Vũng Tàu', 'TP. Hồ Chí Minh'),
    '53': ('82', 'Tiền Giang', 'Đồng Tháp'),
    '54': ('91', 'Kiên Giang', 'An Giang'),
    '55': ('92', 'Cần Thơ', 'Cần Thơ'),
    '56': ('86', 'Bến Tre', 'Vĩnh Long'),
    '57': ('86', 'Vĩnh Long', 'Vĩnh Long'),
    '58': ('86', 'Trà Vinh', 'Vĩnh Long'),
    '59': ('92', 'Sóc Trăng', 'Cần Thơ'),
    '60': ('96', 'Bạc Liêu', 'Cà Mau'),
    '61': ('96', 'Cà Mau', 'Cà Mau'),
    '62': ('11', 'Điện Biên', 'Điện Biên'),
    '63': ('68', 'Đắk Nông', 'Lâm Đồng'),
    '64': ('92', 'Hậu Giang', 'Cần Thơ'),
}
